# Generated by Django 4.1.5 on 2023-06-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Earphone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("cat", models.CharField(max_length=50)),
                ("cmp", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Black", "Black"),
                            ("Red", "Red"),
                            ("white", "white"),
                            ("Green", "Green"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
