# Generated by Django 4.1.5 on 2023-07-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gitt", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Bag", new_name="Git",),
    ]
