# Generated by Django 4.1.5 on 2023-07-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("cat", models.CharField(max_length=50)),
                ("cmp", models.CharField(max_length=50)),
            ],
        ),
    ]
