# Generated by Django 4.1.5 on 2023-06-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Student_Reg_number", models.TextField(unique=True)),
                ("Student_name", models.CharField(max_length=50)),
                ("Student_email", models.TextField()),
                ("Student_mobile", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
