# Generated by Django 4.1.5 on 2023-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Mobile_name", models.CharField(max_length=50)),
                ("Mobile_price", models.IntegerField()),
                ("Cat", models.CharField(max_length=50)),
                ("Cmp", models.CharField(max_length=50)),
            ],
        ),
    ]
